### PR TITLE
Use regex to count letters of any script & Drop foreign chars only if at least one letter still remains

### PR DESCRIPTION
**Pull request by kellnerd**

### CODE REVIEW

**Comment by mayhem** [comment]
Ohh, this looks quite promising, but I managed to break it by adding the following test case:

    ("recording", "Όσο Και Να Σ' Αγαπάω (2018 remaster)", "Όσο Και Να Σ' Αγαπάω"),

give the following failure:

AssertionError: "'" != "Όσο Και Να Σ' Αγαπάω"
- '
+ Όσο Και Να Σ' Αγαπάω

----------------------------------------------------------------------
Ran 55 tests in 0.007s

FAILED (failures=1)

**Comment by kellnerd** [comment]
Hmm, looks like moving the foreign script cleaner after the guff in brackets remover could solve this. I can't test right now because I'm at the wrong computer, but I will try to confirm that later if you haven't already by then.

**Comment by mayhem** [comment]
It seems to move the problem down the road a bit, but I am not entirely which change you suggested. Please have a look later.

**Comment by kellnerd** [comment]
Ok, I think I got it now. Foreign chars are dropped in the last cleaning step for recordings after all the other potential Latin script guff has already been removed.

**Comment by mayhem** [comment]
Oops, should've approved before merging. Clearly I approved!

**Pull request merged**
